
ARG BASE_PERL="5.42"
ARG PERL_IMAGE="dhi.io/perl"
ARG OSNAME="debian"
ARG OSVER="13"
ARG OSLABEL="${BASE_PERL}-${OSNAME}${OSVER}-dev"

ARG USER_NAME=devel
ARG USER_ID=1000
ARG USER_SHELL="/bin/bash"

ARG GROUP_NAME=${USER_NAME}
ARG GROUP_ID=${USER_ID}

ARG USER_HOME="/home/${USER_NAME}"
ARG CACHE_CPANM="${OSNAME}-${OSVER}-cpanm"
ARG CACHE_CPANM_USER="${OSNAME}-${OSVER}-cpanm-${USER_NAME}"
ARG CACHE_PKG_VAR="${OSNAME}-${OSVER}-apt"
ARG CACHE_PKG_LIB="${OSNAME}-${OSVER}-apt-lib"

FROM ${PERL_IMAGE}:${OSLABEL} AS base

ARG CACHE_PKG_LIB
ARG CACHE_PKG_VAR

# Setup apt and some base packages
RUN --mount=type=cache,id=${CACHE_PKG_VAR},target=/var/cache/apt,sharing=locked \
    --mount=type=cache,id=${CACHE_PKG_LIB},target=/var/lib/apt,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean \
    && echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache \
    && apt-get update \
    && apt-get -y install --no-install-recommends \
    adduser \
    git \
    man \
    mandoc \
    manpages


FROM base AS initial-user-env

ARG GROUP_ID
ARG GROUP_NAME
ARG USER_HOME
ARG USER_ID
ARG USER_NAME
ARG USER_SHELL

# Create the user
RUN groupadd --gid "${GROUP_ID}" "${GROUP_NAME}" \
    && useradd --uid "${USER_ID}" --gid "${GROUP_ID}" -m "${USER_NAME}" -s "${USER_SHELL}" -d "${USER_HOME}" \
    && mkdir -p \
    "${USER_HOME}/.ssh" \
    "${USER_HOME}/bin" \
    /workspaces \
    && chmod -R go-rwx /root \
    && chown -R "${USER_NAME}:${GROUP_NAME}" \
    "${USER_HOME}" \
    /workspaces \
    && chmod -R go-rwx "${USER_HOME}/.ssh" \
    && chmod -R u+rwx "${USER_HOME}/bin" \
    && git config --system push.default simple \
    && git config --system init.defaultBranch main

FROM initial-user-env AS add-packages

ARG CACHE_PKG_LIB
ARG CACHE_PKG_VAR

# Base applications
# The Hardened Debian project does not have /etc/debian_version as a config file
# so that upgrading base-files fails. We need to remove it and reinstall base-files
# to prevent errors during package upgrades so that we can get additional security fixes.
RUN --mount=type=cache,id=${CACHE_PKG_VAR},target=/var/cache/apt,sharing=locked \
    --mount=type=cache,id=${CACHE_PKG_LIB},target=/var/lib/apt,sharing=locked \
    apt-get update \
    && rm -f /etc/debian_version \
    && apt-get -y reinstall base-files \
    && apt-get -y upgrade \
    && apt-get -y install --no-install-recommends \
    apt-file \
    curl \
    diffutils \
    expat libexpat1-dev \
    g++ \
    gnu-which \
    gpg \
    less \
    locales \
    locales-all \
    make \
    ncurses-base \
    patch \
    procps \
    rsync \
    ssh \
    tar \
    tmux \
    xz-utils \
    zlib1g zlib1g-dev \
    zsh

FROM add-packages AS install-coro

ARG CACHE_CPANM

# Install patched Coro with its dependencies
RUN --mount=type=cache,id=${CACHE_CPANM},target=/root/.cpanm,sharing=locked \
    --mount=type=bind,source=patches,target=/patches \
    --mount=type=tmpfs,target=/tmp \
    mkdir -p /tmp/build-coro \
    && cd /tmp/build-coro \
    && cp -r /patches/cpanfile . \
    && curl -fLO https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/Coro-6.57.tar.gz \
    && echo '1928e48033540e11ebf5506986dd101af78d2421d210f96599223b15d51714c6 *Coro-6.57.tar.gz' | sha256sum -c - \
    && tar -xaf Coro-6.57.tar.gz \
    && patch -p0 < /patches/Coro-6.57-c23.patch \
    && tar -caf Coro-6.57-patched.tar.gz Coro-6.57 \
    && cpanm --notest --installdeps . \
    && SSL_CERT_DIR=/etc/ssl/certs cpanm --from $PWD Coro-6.57-patched.tar.gz

FROM install-coro AS install-deps

ARG CACHE_CPANM

# Install runtime dependencies
RUN --mount=type=cache,id=${CACHE_CPANM},target=/root/.cpanm,sharing=locked \
    --mount=type=bind,source=cpanfile,target=/tmp/main-env/cpanfile \
    cpanm --notest --installdeps /tmp/main-env

FROM install-deps AS install-developer-deps

ARG CACHE_CPANM

# Install developer dependencies
RUN --mount=type=cache,id=${CACHE_CPANM},target=/root/.cpanm,sharing=locked \
    --mount=type=bind,source=cpanfile,target=/tmp/main-env/cpanfile \
    cpanm --notest --with-develop --installdeps /tmp/main-env

FROM install-developer-deps AS user-env

ARG CACHE_CPANM_USER
ARG CACHE_PKG_VAR
ARG USER_HOME
ARG USER_NAME

USER ${USER_NAME}
