version: "3.9"
name: "schedule-to-html"
services:
  perl:
    image: daphnediane/schedule-to-html:20230708
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
