
ARG BASE_PERL="5.42"
ARG PERL_IMAGE="dhi.io/perl"
ARG OSNAME="debian"
ARG OSVER="13"
ARG OSLABEL="${BASE_PERL}-${OSNAME}${OSVER}-dev"

ARG USER_NAME=devel
ARG USER_ID=1000
ARG USER_SHELL="/bin/bash"

ARG GROUP_NAME=${USER_NAME}
ARG GROUP_ID=${USER_ID}

ARG USER_HOME="/home/${USER_NAME}"
ARG CACHE_CPANM="${OSNAME}-${OSVER}-cpanm"
ARG CACHE_CPANM_USER="${OSNAME}-${OSVER}-cpanm-${USER_NAME}"
ARG CACHE_PKG_VAR="${OSNAME}-${OSVER}-apt"
ARG CACHE_PKG_LIB="${OSNAME}-${OSVER}-apt-lib"

FROM ${PERL_IMAGE}:${OSLABEL} AS base

ARG CACHE_PKG_LIB
ARG CACHE_PKG_VAR

# Setup apt and some base packages
RUN --mount=type=cache,id=${CACHE_PKG_VAR},target=/var/cache/apt,sharing=locked \
    --mount=type=cache,id=${CACHE_PKG_LIB},target=/var/lib/apt,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean \
    && echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache \
    && apt-get update \
    && apt-get -y install --no-install-recommends \
    adduser \
    git \
    man \
    mandoc \
    manpages


FROM base AS initial-user-env

ARG GROUP_ID
ARG GROUP_NAME
ARG USER_HOME
ARG USER_ID
ARG USER_NAME
ARG USER_SHELL

# Create the user
RUN groupadd --gid "${GROUP_ID}" "${GROUP_NAME}" \
    && useradd --uid "${USER_ID}" --gid "${GROUP_ID}" -m "${USER_NAME}" -s "${USER_SHELL}" -d "${USER_HOME}" \
    && mkdir -m 0640 /etc/sudoers.d \
    && echo "${USER_NAME} ALL=(root) NOPASSWD:ALL" > "/etc/sudoers.d/${USER_NAME}" \
    && chmod 0440 "/etc/sudoers.d/${USER_NAME}" \
    && mkdir -p \
    "${USER_HOME}/.ssh" \
    "${USER_HOME}/bin" \
    /home/vscode-server \
    /workspaces \
    && chmod -R go-rwx /root \
    && chown -R "${USER_NAME}:${GROUP_NAME}" \
    "${USER_HOME}" \
    /home/vscode-server \
    /workspaces \
    && chmod -R go-rwx "${USER_HOME}/.ssh" \
    && chmod -R u+rwx "${USER_HOME}/bin" \
    && ln -n -s -f /home/vscode-server "${USER_HOME}/.vscode-server" \
    && git config --system push.default simple \
    && git config --system init.defaultBranch main \
    && mkdir -p \
    /home/vscode-server \
    /workspaces \
    && chown -R "${USER_NAME}:${GROUP_NAME}" \
    /home/vscode-server \
    /workspaces \
    && ln -n -s -f /home/vscode-server "${USER_HOME}/.vscode-server"

FROM initial-user-env AS add-packages

ARG CACHE_PKG_LIB
ARG CACHE_PKG_VAR
ARG GROUP_ID
ARG GROUP_NAME
ARG USER_HOME
ARG USER_ID
ARG USER_NAME
ARG USER_SHELL

# Base applications
RUN --mount=type=cache,id=${CACHE_PKG_VAR},target=/var/cache/apt,sharing=locked \
    --mount=type=cache,id=${CACHE_PKG_LIB},target=/var/lib/apt,sharing=locked \
    apt-get -y install --no-install-recommends \
    apt-file \
    curl \
    diffutils \
    expat libexpat1-dev \
    gpg \
    less \
    lighttpd \
    locales \
    locales-all \
    make \
    nodejs \
    npm \
    patch \
    procps \
    rsync \
    ssh \
    sudo \
    tar \
    tmux \
    xz-utils \
    zlib1g zlib1g-dev \
    zsh

FROM add-packages AS install-deps

ARG CACHE_CPANM

# Install dependencies from cpanfile
RUN --mount=type=cache,id=${CACHE_CPANM},target=/root/.cpanm,sharing=locked \
    --mount=type=bind,source=cpanfile,target=cpanfile \
    cpanm --notest --installdeps .

FROM install-deps AS user-env

ARG USER_HOME
ARG USER_NAME

USER ${USER_NAME}
