version: "3.9"
services:
  schedule-to-html:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OSNAME: "almalinux"
        OSLABEL: "9"
      platforms:
        - "linux/amd64"
    platform: "linux/amd64"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
