requires 'common::sense';
requires 'Scalar::Util';
requires 'AnyEvent', 5.0;
requires 'Storable', 2.15;
requires 'Guard', 0.5;

recommends 'Event', 1.08;
recommends 'EV', 4.0;
recommends 'IO::AIO', 3.1;
recommends 'BDB';
recommends 'AnyEvent', 7.0;
recommends 'AnyEvent::AIO', 1.0;
recommends 'AnyEvent::BDB', 1.0;

on 'build' => sub {
    requires 'ExtUtils::MakeMaker', 6.52;
    requires 'Canary::Stability';
};
