#!/bin/bash

args=()
for i in "" "break" "break_sm"; do
    mkdir -p output/flyers/byday"${i:+_${i}}"
    args+=(
        --
        --pre-title 'day'
        --style print:landscape"${i:+_${i}}".css
        --output output/flyers/byday"${i:+_${i}}"
        --split-day
        --separate
        --hide-unused-rooms
        --file-by-day
    )
done

mkdir -p output/flyers/byroom
args+=(
    --
    --pre-title 'rooms'
    --style print:landscape.css
    --output output/flyers/byroom
    --split-day
    --separate
    --hide-unused-rooms
    --file-by-room
    --hide-unused-rooms
    --section-by-room
    --show-av
)

args+=(
    --
    --style print:landscape.css
    --output output/flyers/single.html
    --split-day
    --separate
    --hide-unused-rooms
)

mkdir -p output/flyers/desc
args+=(
    --
    --pre-title 'day'
    --style print:landscape.css
    --output output/flyers/desc
    --split-day
    --show-descriptions
    --hide-grid
    --hide-unused-rooms
    --file-by-day
)

args+=(
    --
    --pre-title 'legal-grid'
    --style print:legal_grid.css
    --output output/flyers/wide_grid.html
    --split-day
    --show-grid
    --hide-descriptions
    --hide-unused-rooms
)

args+=(
    --
    --pre-title 'legal-desc'
    --style print:legal_desc.css
    --output output/flyers/wide_desc.html
    --just-descriptions
)

args+=(
    --
    --pre-title 'tabloid-grid'
    --style print:poster17x11_grid.css
    --output output/flyers/poster17x11_grid.html
    --split-day
    --show-grid
    --hide-descriptions
    --hide-unused-rooms
)

args+=(
    --
    --pre-title 'tabloid-desc'
    --style print:poster17x11v3.css
    --output output/flyers/poster17x11_desc.html
    --just-descriptions
)

args+=(
    --
    --style print:poster30x20_grid.css
    --output output/flyers/poster30x20_grid.html
    --split-day
    --show-grid
    --hide-descriptions
    --hide-unused-rooms
)

args+=(
    --
    --style print:poster30x20_grid.css
    --output output/flyers/poster30x20_desc.html
    --just-descriptions
)

args+=(
    --
    --style print:portrait.css
    --input input/Test.xlsx
    --output output/flyers/workshop.html
    --just-premium
    --just-descriptions
)

args+=(
    --
    --style print:portrait.css
    --input input/Test.xlsx
    --output output/flyers/kids.html
    --just-kids
    --just-descriptions
)

mkdir -p output/flyers/rooms
args+=(
    --
    --pre-title 'room-posters'
    --style print:poster17x11v3.css
    --input input/Test.xlsx
    --output output/flyers/rooms
    --split-day
    --hide-unused-rooms
    --section-by-room
    --file-by-day
)

args+=(
    --
    --pre-title 'workshop-poster'
    --style print:poster17x11v3.css
    --input input/Test.xlsx
    --output output/flyers/workshop-poster.html
    --show-premium
    --show-kids
    --hide-free
    --just-descriptions
)

mkdir -p output/flyers/guests
args+=(
    --
    --pre-title 'guests'
    --style print:landscape.css
    --output output/flyers/guests/
    --split-day
    --separate
    --hide-paneltype BR
    --show-paneltype SM
    --show-breaks
    --hide-unused-rooms
    --file-by-guest
)

mkdir -p output/flyers/judges
args+=(
    --
    --pre-title 'judges'
    --style print:landscape.css
    --output output/flyers/judges/
    --split-day
    --separate
    --hide-paneltype BR
    --show-paneltype SM
    --show-breaks
    --hide-unused-rooms
    --file-by-judge
)

mkdir -p output/flyers/staff
args+=(
    --
    --pre-title 'staff'
    --style print:landscape.css
    --output output/flyers/staff/
    --split-day
    --separate
    --hide-paneltype BR
    --show-paneltype SM
    --show-breaks
    --hide-unused-rooms
    --file-by-staff
)

mkdir -p output/flyers/panelists
args+=(
    --
    --pre-title 'panelist'
    --style print:landscape.css
    --output output/flyers/panelists/
    --split-day
    --separate
    --hide-unused-rooms
    --file-by-presenter
    --no-file-by-guest
    --no-file-by-judge
)

args+=(
    --
    --style print:landscape.css
    --output output/flyers/single_staff.html
    --split-day
    --separate
    --hide-paneltype BR
    --show-paneltype SM
    --show-breaks
    --hide-unused-rooms
)

args+=(
    --
    --style print:legal_grid.css
    --output output/flyers/staff.html
    --split-day
    --show-grid
    --hide-paneltype BR
    --show-paneltype SM
    --show-breaks
    --hide-descriptions
    --hide-unused-rooms
)

args+=(
    --
    --style print:guest-quarter.css
    --output output/flyers/postcards-guests.html
    --split-timeregion
    --section-by-guest
    --section-by-day
    --hide-paneltype BR
    --show-paneltype SM
    --show-presenter-on-grid
    --hide-descriptions
    --hide-unused
)

args+=(
    --
    --style print:guest-quarter.css
    --output output/flyers/postcards-judges.html
    --split-timeregion
    --section-by-judge
    --section-by-day
    --hide-paneltype BR
    --show-paneltype SM
    --show-presenter-on-grid
    --hide-descriptions
    --hide-unused
)

args+=(
    --
    --style print:guest-quarter.css
    --output output/flyers/postcards-staff.html
    --split-timeregion
    --section-by-staff
    --section-by-day
    --hide-paneltype BR
    --show-paneltype SM
    --show-presenter-on-grid
    --hide-descriptions
    --hide-unused
)

./schedule_html \
    --input input/Test.xlsx \
    "$@" \
    "${args[@]}"
