#!/bin/sh

./desc_tbl \
    --style license-fonts.css \
    --style common.css \
    --style screen.css \
    --style screen:color.css \
    --style screen:+color \
    --style print.css \
    --style screen:+color=BW \
    --style print:bw.css \
    "$@"
