#!/bin/sh

dir=$(dirname "$0")
perl -I "${dir}/lib" -I "${dir}/local/lib/perl5" -- "${dir}/lib/main.pm" \
    --style common.css \
    --style screen.css \
    --style screen:color.css \
    --style screen:+color \
    --style print.css \
    --style print:+color=BW \
    --style print:bw.css \
    "$@"
